                <!-- START X-NAVIGATION -->
                <ul class="x-navigation">
                    <li class="xn">
                        <a href="dasbor.php"><center><font size="4" face="verdana" color="white">INDOSOSMED Corp.</font></b></center></a>
                        <a href="#" class="x-navigation-control"></a>
                    </li>
                    <li class="xn-profile">
                        <a href="#" class="profile-mini">
                            <img src="assets/images/users/avatar.jpg" alt="John Doe"/>
                        </a>
                        <div class="profile">
                            <div class="profile-image">
                                <img src="assets/images/users/avatar.jpg" alt="John Doe"/>
                            </div>
                            <div class="profile-data">
                                <div class="profile-data-name"><?php echo"$username";?></div>
                                <div class="profile-data-title">Member <?php echo"$site";?></div>
                            </div>
                            <div class="profile-controls">
                                <a href="#" class="profile-control-left"><span class="fa fa-info"></span></a>
                                <a href="#" class="profile-control-right"><span class="fa fa-envelope"></span></a>
                            </div>
                        </div>                                                                     
                    </li>
                    
                                        <li class="xn-openable">
                        <a href="#"><span class="fa fa-tags"></span> <span class="xn-text">Harga</span></a>
                        <ul>
                        <li><a href="harga.php"><span class="fa fa-globe"></span>Sosial Media</a></li>
                            <li><a href="hargapulsa.php"><span class="fa fa-mobile-phone"></span>Pulsa</a></li>
                           </ul>
                    </li>                  
                    </li>                
              <ul>
              <li class="xn-openable">
                        <a href="#"><span class="fa fa-gittip"></span> <span class="xn-text">Baca Dahulu</span></a>
                        <ul>
                            <li><a href="faq.php"><span class="fa fa-bullhorn"></span>FAQ</a></li>
                            <li><a href="trems.php"><span class="fa fa-info"></span> TERMS</a></li>
                            <li><a href="peraturan.php"><span class="fa fa-key"></span> PERATURAN! (PENTING)</a></li>
                           </ul>
                    </li>                    

                <!-- END X-NAVIGATION -->