                <!-- START X-NAVIGATION -->
                <ul class="x-navigation">
                    <li class="xn">
                        <a href="dasbor.php"><center><font size="4" face="verdana" color="white">INDOSOSMED Corp.</font></b></center></a>
                        <a href="#" class="x-navigation-control"></a>
                    </li>
                    <li class="xn-profile">
                        <a href="#" class="profile-mini">
                            <img src="assets/images/users/avatar.jpg" alt="John Doe"/>
                        </a>
                        <div class="profile">
                            <div class="profile-image">
                                <img src="assets/images/users/avatar.jpg" alt="John Doe"/>
                            </div>
                            <div class="profile-data">
                                <div class="profile-data-name"><?php echo"$username";?></div>
                                <div class="profile-data-title">Member <?php echo"$site";?></div>
                            </div>
                            <div class="profile-controls">
                                <a href="#" class="profile-control-left"><span class="fa fa-info"></span></a>
                                <a href="#" class="profile-control-right"><span class="fa fa-envelope"></span></a>
                            </div>
                        </div>                                                                     
                    </li>
                    
                    <li class="active">
                        <a href="dasbor.php"><span class="fa fa-desktop"></span> <span class="xn-text">Dashboard</span></a>                        
                    </li>  
                                        <li class="xn-openable">
                        <a href="#"><span class="fa fa-tags"></span> <span class="xn-text">Harga</span></a>
                        <ul>
                        <li><a href="harga.php" target="_blank"><span class="fa fa-globe"></span>Sosial Media</a></li>
                            <li><a href="hargapulsa.php" target="_blank"><span class="fa fa-mobile-phone"></span>Pulsa</a></li>
                           </ul>
                    </li>                  
                    <li class="xn-openable">
                        <a href="#"><span class="fa fa-shopping-cart"></span> <span class="xn-text">Order</span></a>
                        <ul>
                        
                            <li><a href="order.php"><span class="fa fa-globe"></span> Sosial Media</a></li>
                            <li><a href="orderpulsa.php"><span class="fa fa-mobile-phone"></span> Pulsa</a></li>
                            
                                                     
                        </ul>
                    </li>
                    <li class="xn-openable">
                        <a href="#"><span class="fa fa-refresh"></span> <span class="xn-text">Riwayat</span></a>
                        <ul>
                            <li><a href="histori.php"><span class="fa fa-globe"></span>Sosial Media</a></li>
                            <li><a href="historipulsa.php"><span class="fa fa-mobile-phone"></span> Pulsa</a></li>
                           </ul>
                    </li>
                   <li class="xn-openable">
                        <a href="#"><span class="fa fa-money"></span> <span class="xn-text">Top UP Saldo</span></a>
                        <ul>
                            <li><a href="bank.php"><span class="fa fa-usd"></span>Bank</a></li>
                            <li><a href="topuppulsa.php"><span class="fa fa-mobile-phone"></span> Pulsa</a></li>
                              <li><a href="historisaldo.php"><span class="fa fa-refresh"></span> Riwayat</span></a></li>
                           </ul>
                    </li>                    
              <ul>
              <li class="xn-openable">
                        <a href="#"><span class="fa fa-gittip"></span> <span class="xn-text">Baca Dahulu</span></a>
                        <ul>
                            <li><a href="faq.php"><span class="fa fa-bullhorn"></span>FAQ</a></li>
                            <li><a href="trems.php"><span class="fa fa-info"></span> TERMS</a></li>
                            <li><a href="peraturan.php"><span class="fa fa-key"></span> PERATURAN! (PENTING)</a></li>
                           </ul>
                    </li>                    
              <ul>
              <li><a href="pengaturan.php"><span class="fa fa-gear"></span> Setting</a></li>
                            </ul>
                            <li><a href="logout.php"><span class="fa fa-sign-out"></span> SignOut</a></li>
                            </ul>
                <!-- END X-NAVIGATION -->